// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package iam

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID             int64          `db:"id" json:"id"`
	PublicID       uuid.UUID      `db:"public_id" json:"public_id"`
	UserID         sql.NullInt64  `db:"user_id" json:"user_id"`
	Action         string         `db:"action" json:"action"`
	EntityType     string         `db:"entity_type" json:"entity_type"`
	EntityID       int64          `db:"entity_id" json:"entity_id"`
	EntityPublicID uuid.UUID      `db:"entity_public_id" json:"entity_public_id"`
	OldValues      sql.NullString `db:"old_values" json:"old_values"`
	NewValues      sql.NullString `db:"new_values" json:"new_values"`
	PrevHash       sql.NullString `db:"prev_hash" json:"prev_hash"`
	CurrHash       string         `db:"curr_hash" json:"curr_hash"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
}

type IamSession struct {
	ID        int64        `db:"id" json:"id"`
	PublicID  uuid.UUID    `db:"public_id" json:"public_id"`
	UserID    int64        `db:"user_id" json:"user_id"`
	TokenHash string       `db:"token_hash" json:"token_hash"`
	ExpiresAt time.Time    `db:"expires_at" json:"expires_at"`
	RevokedAt sql.NullTime `db:"revoked_at" json:"revoked_at"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
}

type IamUser struct {
	ID           int64          `db:"id" json:"id"`
	PublicID     uuid.UUID      `db:"public_id" json:"public_id"`
	Email        string         `db:"email" json:"email"`
	Name         string         `db:"name" json:"name"`
	PasswordHash sql.NullString `db:"password_hash" json:"password_hash"`
	IsActive     bool           `db:"is_active" json:"is_active"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
	DeletedAt    sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type IdempotencyKey struct {
	ID                  int64          `db:"id" json:"id"`
	IdempotencyKey      uuid.UUID      `db:"idempotency_key" json:"idempotency_key"`
	UserID              int64          `db:"user_id" json:"user_id"`
	RequestPath         string         `db:"request_path" json:"request_path"`
	RequestMethod       string         `db:"request_method" json:"request_method"`
	RequestHash         string         `db:"request_hash" json:"request_hash"`
	Status              string         `db:"status" json:"status"`
	ResponseStatus      sql.NullInt32  `db:"response_status" json:"response_status"`
	ResponseBody        sql.NullString `db:"response_body" json:"response_body"`
	ResponseContentType sql.NullString `db:"response_content_type" json:"response_content_type"`
	ExpiresAt           time.Time      `db:"expires_at" json:"expires_at"`
	CreatedAt           time.Time      `db:"created_at" json:"created_at"`
}

type OutboxEvent struct {
	ID            int64           `db:"id" json:"id"`
	UserID        sql.NullInt64   `db:"user_id" json:"user_id"`
	EventType     string          `db:"event_type" json:"event_type"`
	Payload       json.RawMessage `db:"payload" json:"payload"`
	CorrelationID sql.NullString  `db:"correlation_id" json:"correlation_id"`
	Status        string          `db:"status" json:"status"`
	Attempts      int32           `db:"attempts" json:"attempts"`
	NextAttemptAt sql.NullTime    `db:"next_attempt_at" json:"next_attempt_at"`
	PublishedAt   sql.NullTime    `db:"published_at" json:"published_at"`
	CreatedAt     time.Time       `db:"created_at" json:"created_at"`
}

type Task struct {
	ID          int64         `db:"id" json:"id"`
	PublicID    uuid.UUID     `db:"public_id" json:"public_id"`
	UserID      int64         `db:"user_id" json:"user_id"`
	Title       string        `db:"title" json:"title"`
	Description string        `db:"description" json:"description"`
	Status      string        `db:"status" json:"status"`
	AssigneeID  sql.NullInt64 `db:"assignee_id" json:"assignee_id"`
	CreatedAt   time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time     `db:"updated_at" json:"updated_at"`
}

type TaskLog struct {
	ID            int64         `db:"id" json:"id"`
	TaskID        int64         `db:"task_id" json:"task_id"`
	UserID        int64         `db:"user_id" json:"user_id"`
	Action        string        `db:"action" json:"action"`
	OldAssigneeID sql.NullInt64 `db:"old_assignee_id" json:"old_assignee_id"`
	NewAssigneeID sql.NullInt64 `db:"new_assignee_id" json:"new_assignee_id"`
	ActorUserID   sql.NullInt64 `db:"actor_user_id" json:"actor_user_id"`
	CreatedAt     time.Time     `db:"created_at" json:"created_at"`
}
