// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package iam

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO iam.sessions (public_id, user_id, token_hash, expires_at)
VALUES (public.uuid_generate_v7(), $1, $2, $3)
RETURNING id, public_id, user_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    int64     `db:"user_id" json:"user_id"`
	TokenHash string    `db:"token_hash" json:"token_hash"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

type CreateSessionRow struct {
	ID        int64     `db:"id" json:"id"`
	PublicID  uuid.UUID `db:"public_id" json:"public_id"`
	UserID    int64     `db:"user_id" json:"user_id"`
	TokenHash string    `db:"token_hash" json:"token_hash"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO iam.users (public_id, email, name, password_hash, is_active)
VALUES (public.uuid_generate_v7(), $1, $2, $3, true)
RETURNING id, public_id, email, name, password_hash, is_active, created_at
`

type CreateUserParams struct {
	Email        string         `db:"email" json:"email"`
	Name         string         `db:"name" json:"name"`
	PasswordHash sql.NullString `db:"password_hash" json:"password_hash"`
}

type CreateUserRow struct {
	ID           int64          `db:"id" json:"id"`
	PublicID     uuid.UUID      `db:"public_id" json:"public_id"`
	Email        string         `db:"email" json:"email"`
	Name         string         `db:"name" json:"name"`
	PasswordHash sql.NullString `db:"password_hash" json:"password_hash"`
	IsActive     bool           `db:"is_active" json:"is_active"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, public_id, user_id, token_hash, expires_at, created_at, revoked_at
FROM iam.sessions
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

type GetSessionByTokenHashRow struct {
	ID        int64        `db:"id" json:"id"`
	PublicID  uuid.UUID    `db:"public_id" json:"public_id"`
	UserID    int64        `db:"user_id" json:"user_id"`
	TokenHash string       `db:"token_hash" json:"token_hash"`
	ExpiresAt time.Time    `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	RevokedAt sql.NullTime `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, public_id, email, name, password_hash, is_active, created_at
FROM iam.users
WHERE lower(email) = lower($1) AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID           int64          `db:"id" json:"id"`
	PublicID     uuid.UUID      `db:"public_id" json:"public_id"`
	Email        string         `db:"email" json:"email"`
	Name         string         `db:"name" json:"name"`
	PasswordHash sql.NullString `db:"password_hash" json:"password_hash"`
	IsActive     bool           `db:"is_active" json:"is_active"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, email, name, password_hash, is_active, created_at
FROM iam.users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID           int64          `db:"id" json:"id"`
	PublicID     uuid.UUID      `db:"public_id" json:"public_id"`
	Email        string         `db:"email" json:"email"`
	Name         string         `db:"name" json:"name"`
	PasswordHash sql.NullString `db:"password_hash" json:"password_hash"`
	IsActive     bool           `db:"is_active" json:"is_active"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE iam.sessions SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, revokeSession, tokenHash)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO iam.users (public_id, email, name, password_hash, is_active)
VALUES (public.uuid_generate_v7(), $1, $2, $3, true)
ON CONFLICT (lower(email)) WHERE deleted_at IS NULL DO UPDATE
  SET name = EXCLUDED.name, password_hash = EXCLUDED.password_hash
RETURNING id, public_id, email, name, password_hash, is_active, created_at
`

type UpsertUserParams struct {
	Email        string         `db:"email" json:"email"`
	Name         string         `db:"name" json:"name"`
	PasswordHash sql.NullString `db:"password_hash" json:"password_hash"`
}

type UpsertUserRow struct {
	ID           int64          `db:"id" json:"id"`
	PublicID     uuid.UUID      `db:"public_id" json:"public_id"`
	Email        string         `db:"email" json:"email"`
	Name         string         `db:"name" json:"name"`
	PasswordHash sql.NullString `db:"password_hash" json:"password_hash"`
	IsActive     bool           `db:"is_active" json:"is_active"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (UpsertUserRow, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, arg.Email, arg.Name, arg.PasswordHash)
	var i UpsertUserRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
