// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package tasks

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const assignTask = `-- name: AssignTask :one
UPDATE public.tasks
SET assignee_id = $2, updated_at = now()
WHERE public_id = $1 AND user_id = $3
RETURNING id, public_id, user_id, title, description, status, assignee_id, created_at, updated_at
`

type AssignTaskParams struct {
	PublicID   uuid.UUID     `db:"public_id" json:"public_id"`
	AssigneeID sql.NullInt64 `db:"assignee_id" json:"assignee_id"`
	UserID     int64         `db:"user_id" json:"user_id"`
}

func (q *Queries) AssignTask(ctx context.Context, arg AssignTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, assignTask, arg.PublicID, arg.AssigneeID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO public.tasks (user_id, title, description, status)
VALUES ($1, $2, $3, $4)
RETURNING id, public_id, user_id, title, description, status, assignee_id, created_at, updated_at
`

type CreateTaskParams struct {
	UserID      int64  `db:"user_id" json:"user_id"`
	Title       string `db:"title" json:"title"`
	Description string `db:"description" json:"description"`
	Status      string `db:"status" json:"status"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM public.tasks
WHERE user_id = $1 AND public_id = $2
`

type DeleteTaskParams struct {
	UserID   int64     `db:"user_id" json:"user_id"`
	PublicID uuid.UUID `db:"public_id" json:"public_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTask, arg.UserID, arg.PublicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findActiveUser = `-- name: FindActiveUser :one
SELECT id
FROM iam.users
WHERE id = $1 AND is_active = true AND deleted_at IS NULL
`

func (q *Queries) FindActiveUser(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, findActiveUser, id)
	err := row.Scan(&id)
	return id, err
}

const findTask = `-- name: FindTask :one
SELECT id, public_id, user_id, title, description, status, assignee_id, created_at, updated_at
FROM public.tasks
WHERE user_id = $1 AND public_id = $2
`

type FindTaskParams struct {
	UserID   int64     `db:"user_id" json:"user_id"`
	PublicID uuid.UUID `db:"public_id" json:"public_id"`
}

func (q *Queries) FindTask(ctx context.Context, arg FindTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, findTask, arg.UserID, arg.PublicID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTaskLog = `-- name: InsertTaskLog :exec
INSERT INTO public.task_logs (task_id, user_id, action, old_assignee_id, new_assignee_id, actor_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTaskLogParams struct {
	TaskID        int64         `db:"task_id" json:"task_id"`
	UserID        int64         `db:"user_id" json:"user_id"`
	Action        string        `db:"action" json:"action"`
	OldAssigneeID sql.NullInt64 `db:"old_assignee_id" json:"old_assignee_id"`
	NewAssigneeID sql.NullInt64 `db:"new_assignee_id" json:"new_assignee_id"`
	ActorUserID   sql.NullInt64 `db:"actor_user_id" json:"actor_user_id"`
}

func (q *Queries) InsertTaskLog(ctx context.Context, arg InsertTaskLogParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskLog,
		arg.TaskID,
		arg.UserID,
		arg.Action,
		arg.OldAssigneeID,
		arg.NewAssigneeID,
		arg.ActorUserID,
	)
	return err
}

const listTasks = `-- name: ListTasks :many
SELECT id, public_id, user_id, title, description, status, assignee_id, created_at, updated_at
FROM public.tasks
WHERE user_id = $1
  AND status = COALESCE($2, status)
  AND title ILIKE COALESCE($3::VARCHAR, title)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListTasksParams struct {
	UserID        int64          `db:"user_id" json:"user_id"`
	StatusFilter  sql.NullString `db:"status_filter" json:"status_filter"`
	SearchPattern sql.NullString `db:"search_pattern" json:"search_pattern"`
	OffsetRows    int32          `db:"offset_rows" json:"offset_rows"`
	LimitRows     int32          `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.UserID,
		arg.StatusFilter,
		arg.SearchPattern,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE public.tasks
SET title = $3, description = $4, status = $5, updated_at = now()
WHERE user_id = $1 AND public_id = $2
RETURNING id, public_id, user_id, title, description, status, assignee_id, created_at, updated_at
`

type UpdateTaskParams struct {
	UserID      int64     `db:"user_id" json:"user_id"`
	PublicID    uuid.UUID `db:"public_id" json:"public_id"`
	Title       string    `db:"title" json:"title"`
	Description string    `db:"description" json:"description"`
	Status      string    `db:"status" json:"status"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.UserID,
		arg.PublicID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
